import { StyleSheet } from "react-native";
import { Design, FontFamily } from "@/src/constants/design";

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 36,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  closeButton: {
    padding: 4,
  },
  bannerCard: {
    backgroundColor: "#F0F7F2",
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    marginBottom: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E2EFE5",
  },
  bannerTextContainer: {
    flex: 1,
    paddingRight: 8,
  },
  bannerTitle: {
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 15,
    color: Design.colors.black,
    lineHeight: 22,
  },
  bannerImage: {
    width: 110,
    height: 100,
  },
  activeSubCard: {
    backgroundColor: "#FFFBEB",
    borderColor: "#FDE68A",
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginBottom: 16,
  },
  activeSubHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  activeSubTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  activeSubTitle: {
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 13,
    color: "#92400E",
  },
  activeSubPlanName: {
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 16,
    color: Design.colors.black,
    marginVertical: 2,
  },
  activeSubMetaText: {
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: 12,
    color: "#78350F",
  },
  loadingContainer: {
    paddingVertical: 40,
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: 13,
    color: Design.colors.mutedText,
  },
  packageList: {
    gap: 14,
  },
  packageCard: {
    borderWidth: 1,
    borderColor: Design.colors.optionBorder,
    borderRadius: 20,
    padding: 16,
    backgroundColor: Design.colors.white,
    position: "relative",
  },
  packageCardPressed: {
    opacity: 0.95,
  },
  packageCardSelected: {
    borderColor: Design.colors.primaryGreen,
    backgroundColor: "#FCFCFC",
  },
  radioContainer: {
    position: "absolute",
    top: 14,
    right: 14,
    zIndex: 2,
  },
  badgePill: {
    backgroundColor: "#DCFCE7",
    borderColor: "#86EFAC",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 1,
    alignSelf: "center",
  },
  badgeText: {
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 10,
    color: "#166534",
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Design.colors.mutedText,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Design.colors.white,
  },
  radioCircleSelected: {
    borderColor: Design.colors.primaryGreen,
  },
  radioInnerDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Design.colors.primaryGreen,
  },
  packageContentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  packageLeftCol: {
    width: "45%",
    paddingRight: 6,
  },
  packageTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: 6,
  },
  crownIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  crownEmoji: {
    fontSize: 22,
  },
  packageTitle: {
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 15,
    color: Design.colors.black,
  },
  packagePrice: {
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 14,
    color: Design.colors.primaryGreen,
  },
  packageDuration: {
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: 11,
    color: Design.colors.mutedText,
  },
  activeTag: {
    alignSelf: "flex-start",
    backgroundColor: "#E0F2FE",
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginTop: 6,
  },
  activeTagText: {
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: 10,
    color: "#0369A1",
  },
  featuresBox: {
    width: "55%",
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    padding: 10,
    paddingRight: 20,
    gap: 7,
  },
  featureRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  featureText: {
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: 11,
    color: Design.colors.black,
    flex: 1,
    lineHeight: 16,
  },
  featureTextDisabled: {
    color: Design.colors.mutedText,
  },
  footer: {
    marginTop: 20,
    gap: 12,
  },
  noticeBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F7F2",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    gap: 10,
  },
  noticeText: {
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: 13,
    color: Design.colors.black,
  },
  actionButton: {
    width: "100%",
    borderRadius: 24,
  },
  secureRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 4,
  },
  secureText: {
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: 12,
    color: Design.colors.mutedText,
  },
});
