import { Design, FontFamily } from '@/src/constants/design';
import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  rootContainer: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: 'transparent' },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 4,
    justifyContent: 'space-between',
  },
  scrollContentImmersive: { justifyContent: 'space-between', paddingBottom: 32 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerContainer: { gap: 4 },
  headerStatsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  headerActions: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  iconHeaderButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    borderColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 18,
    borderWidth: 1,
    elevation: 2,
    height: 36,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    width: 36,
  },
  iconHeaderButtonNight: {
    backgroundColor: 'rgba(30, 41, 59, 0.82)',
    borderColor: 'rgba(255, 255, 255, 0.25)',
    elevation: 3,
    shadowOpacity: 0.25,
  },
  immersiveButtonActive: { backgroundColor: '#DCFCE7', borderColor: '#4ADE80' },
  immersiveButtonActiveNight: {
    backgroundColor: 'rgba(56, 189, 248, 0.25)',
    borderColor: '#38BDF8',
  },
  greeting: {
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.h2 - 2,
    color: '#0F291E',
    marginBottom: 4,
    flexShrink: 1,
  },
  greetingNight: {
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  notificationButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    borderColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 18,
    borderWidth: 1,
    elevation: 2,
    height: 36,
    justifyContent: 'center',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    width: 36,
  },
  notificationButtonNight: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  notificationBadge: {
    backgroundColor: '#E34D59',
    borderColor: Design.colors.white,
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    position: 'absolute',
    right: 5,
    top: 4,
    width: 10,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3D9C6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  avatarNight: { borderColor: 'rgba(255, 255, 255, 0.65)' },
  avatarText: {
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
    color: Design.colors.black,
  },
  avatarTextNight: { color: Design.colors.black },
  statPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'transparent',
    paddingVertical: 2,
    paddingHorizontal: 4,
  },
  statIcon: { height: 22, width: 22 },
  statValue: { fontFamily: FontFamily.beVietnamSemiBold, fontSize: 15 },
  streakValue: { color: '#EA580C' },
  streakValueNight: { color: '#FB923C' },
  rubyValue: { color: '#E11D48' },
  rubyValueNight: { color: '#FB7185' },
  mascotCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 4,
  },
  mascot: { width: 290, height: 300 },
  mascotCardImmersive: { marginTop: 36, marginBottom: 16 },
  bottomCardSection: { width: '100%', marginBottom: 4 },
  wardrobeIconButton: {
    alignSelf: 'flex-end',
    marginBottom: 6,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderWidth: 1,
    borderColor: '#D6E8D3',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 3,
  },
  wardrobeIconButtonNight: {
    backgroundColor: 'rgba(26, 36, 54, 0.9)',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowOpacity: 0.25,
  },
  immersiveHintPill: {
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    borderColor: '#86EFAC',
    borderRadius: 20,
    borderWidth: 1,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 24,
    marginBottom: 20,
    paddingHorizontal: 16,
    paddingVertical: 9,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  immersiveHintPillNight: {
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    borderColor: 'rgba(56, 189, 248, 0.4)',
    shadowOpacity: 0.35,
  },
  immersiveHintText: {
    color: '#15803D',
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: 12,
  },
  immersiveHintTextNight: { color: '#BAE6FD' },
  notificationModal: {
    backgroundColor: Design.colors.white,
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 48 : 24,
  },
  notificationHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 56,
    paddingVertical: 14,
  },
  notificationHeaderActions: { alignItems: 'center', flexDirection: 'row', gap: 14 },
  friendRequestsLink: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  friendRequestsLinkText: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption,
  },
  markAllLink: { alignItems: 'center', justifyContent: 'center' },
  markAllLinkText: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption,
  },
  notificationCloseButton: { alignItems: 'center', height: 40, justifyContent: 'center', width: 40 },
  notificationTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.title,
  },
  notificationError: {
    color: '#B33A3A',
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginVertical: 12,
  },
  emptyNotifications: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    paddingVertical: 24,
    textAlign: 'center',
  },
  notificationItem: {
    alignItems: 'center',
    borderBottomColor: '#E9E9E9',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 14,
  },
  notificationText: {
    color: Design.colors.black,
    flex: 1,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
  },
  unreadNotificationText: { fontFamily: FontFamily.beVietnamSemiBold },
  bottomBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
  },
  roundButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: Design.colors.primaryGreen,
    alignItems: 'center',
    justifyContent: 'center',
  },
  roundButtonOutline: {
    backgroundColor: Design.colors.white,
    borderWidth: 1,
    borderColor: Design.colors.black,
  },
  togglePill: { flex: 1, marginHorizontal: 12 },
});
