import { Design, FontFamily } from "@/src/constants/design";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#F8FAF7",
    flex: 1,
  },
  header: {
    alignItems: "center",
    backgroundColor: Design.colors.white,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#EDF5EE",
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "#F1F5F9",
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  headerTitleWrap: {
    flex: 1,
    marginLeft: 12,
  },
  headerTitle: {
    color: "#0F291E",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 18,
  },
  headerSubtitle: {
    color: "#64748B",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: 11,
    marginTop: 1,
  },
  inventoryCountBadge: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  inventoryCountText: {
    color: "#059669",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 12,
  },
  content: {
    gap: 16,
    padding: 18,
    paddingBottom: 36,
  },
  loading: {
    alignItems: "center",
    gap: 12,
    paddingVertical: 60,
  },
  loadingText: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
  },
  errorCard: {
    alignItems: "center",
    backgroundColor: "#FFF1F0",
    borderRadius: 14,
    gap: 12,
    padding: 16,
  },
  errorText: {
    color: "#A93232",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: Design.colors.primaryGreen,
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  retryText: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption,
  },
  previewCard: {
    backgroundColor: Design.colors.white,
    borderColor: "#D1FAE5",
    borderRadius: 22,
    borderWidth: 1.5,
    padding: 16,
    shadowColor: "#10B981",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  previewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  previewBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#ECFDF5",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#A7F3D0",
  },
  previewBadgeText: {
    color: "#065F46",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 12,
  },
  previewLayersCount: {
    color: "#64748B",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: 12,
  },
  avatarPreview: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0FDF4",
    borderColor: "#DCFCE7",
    borderRadius: 18,
    borderWidth: 1,
    height: 280,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  emptyAvatar: {
    alignSelf: "center",
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    marginTop: 120,
  },
  inventorySection: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  emptyInventory: {
    backgroundColor: Design.colors.white,
    borderColor: "#E2EFE6",
    borderRadius: 16,
    borderWidth: 1,
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    padding: 24,
    textAlign: "center",
    width: "100%",
  },
  inventoryCard: {
    backgroundColor: Design.colors.white,
    borderColor: "#E2EFE6",
    borderRadius: 18,
    borderWidth: 1.5,
    marginBottom: 14,
    padding: 10,
    width: "48%",
    shadowColor: "#10B981",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  slotBadge: {
    backgroundColor: "#F1F5F9",
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  slotBadgeText: {
    color: "#475569",
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: 10,
  },
  equippedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "#ECFDF5",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  equippedBadgeText: {
    color: "#059669",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 10,
  },
  itemImageShowcase: {
    alignItems: "center",
    backgroundColor: "#F8FAF8",
    borderRadius: 14,
    height: 96,
    justifyContent: "center",
    marginBottom: 8,
    width: "100%",
  },
  itemImage: {
    height: 84,
    width: "84%",
  },
  itemName: {
    color: "#0F291E",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 12.5,
    marginBottom: 8,
    textAlign: "center",
  },
  itemAction: {
    alignItems: "center",
    backgroundColor: Design.colors.primaryGreen,
    borderRadius: 10,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: 10,
    width: "100%",
    shadowColor: "#10B981",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  unequipAction: {
    backgroundColor: "#FFF1F2",
    borderColor: "#FECDD3",
    borderWidth: 1,
    shadowOpacity: 0,
    elevation: 0,
  },
  baseItemAction: {
    backgroundColor: "#F1F5F9",
    shadowOpacity: 0,
    elevation: 0,
  },
  itemActionPressed: {
    transform: [{ scale: 0.96 }],
  },
  itemActionText: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 11,
  },
  unequipActionText: {
    color: "#E11D48",
  },
  baseItemActionText: {
    color: "#64748B",
  },
  actionError: {
    backgroundColor: "#FFF1F0",
    borderRadius: 12,
    color: "#A93232",
    fontFamily: FontFamily.beVietnamRegular,
    marginBottom: 12,
    padding: 12,
    width: "100%",
  },
});
