import { StyleSheet } from "react-native";
import { Design, FontFamily } from "@/src/constants/design";

export const styles = StyleSheet.create({
  safeArea: { backgroundColor: Design.colors.white, flex: 1 },
  flex: { flex: 1 },
  content: { flex: 1 },
  cardPressed: { opacity: 0.8 },
  commentsLoader: { marginVertical: 8 },
  feedTabs: {
    borderBottomColor: "#E9E9E9",
    borderBottomWidth: 1,
    flexDirection: "row",
    marginBottom: 12,
    marginHorizontal: 20,
  },
  feedTab: {
    alignItems: "center",
    flex: 1,
    paddingBottom: 11,
    paddingTop: 4,
  },
  feedTabActive: {
    borderBottomColor: Design.colors.primaryGreen,
    borderBottomWidth: 2,
  },
  feedTabText: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 2,
  },
  feedTabTextActive: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.beVietnamSemiBold,
  },
  suggestionsSection: {
    backgroundColor: "#F8FAF8",
    borderColor: "#EAF3ED",
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 14,
    marginHorizontal: 20,
    padding: 14,
  },
  suggestionsHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  suggestionsTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
  },
  suggestionsSubtitle: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption,
    marginTop: 2,
  },
  suggestionsList: { gap: 10 },
  suggestionCard: {
    backgroundColor: Design.colors.white,
    borderColor: "#E9E9E9",
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 145,
    padding: 10,
    width: 130,
  },
  suggestionProfileButton: {
    alignItems: "center",
  },
  suggestionAvatar: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#F5D6DE",
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    marginBottom: 8,
    overflow: "hidden",
    width: 48,
  },
  suggestionAvatarImage: { height: "100%", width: "100%" },
  suggestionAvatarText: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
  },
  suggestionName: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 1,
    textAlign: "center",
  },
  suggestionReason: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption - 1,
    lineHeight: 15,
    marginTop: 4,
    textAlign: "center",
  },
  suggestionMutual: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption - 1,
    marginTop: 4,
    textAlign: "center",
  },
  addFriendButton: {
    alignItems: "center",
    backgroundColor: Design.colors.primaryGreen,
    borderRadius: 16,
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  addFriendButtonText: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption - 1,
  },
  noSuggestionsText: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    paddingHorizontal: 24,
    paddingTop: 8,
  },
  backButton: { width: 32 },
  friendRequestsButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  headerTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.title,
  },
  composer: {
    alignItems: "center",
    borderColor: "#E9E9E9",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    height: 52,
    marginBottom: 16,
    marginHorizontal: 20,
    paddingHorizontal: 12,
  },
  composerInput: {
    color: Design.colors.black,
    flex: 1,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
    paddingVertical: 0,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: "#F5D6DE",
    borderRadius: 16,
    height: 32,
    justifyContent: "center",
    overflow: "hidden",
    width: 32,
  },
  avatarImage: { backgroundColor: "#E6E6E6", height: "100%", width: "100%" },
  avatarImageOverlay: { alignItems: "center", flex: 1, justifyContent: "center" },
  avatarText: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  scrollContent: { paddingBottom: 28, paddingHorizontal: 20 },
  postCard: {
    backgroundColor: Design.colors.white,
    borderColor: "#EDEDED",
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 16,
    padding: 12,
  },
  postHeader: { alignItems: "center", flexDirection: "row", marginBottom: 10 },
  postAuthorWrap: { flex: 1, marginLeft: 10 },
  postAuthor: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  postTimestamp: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption - 1,
  },
  postImageWrap: {
    backgroundColor: "#111111",
    borderRadius: 12,
    height: 210,
    marginBottom: 10,
    overflow: "hidden",
  },
  postVideo: { height: "100%", width: "100%" },
  postCaption: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
    lineHeight: 18,
    marginBottom: 4,
  },
  postTags: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginBottom: 8,
  },
  actionRow: { flexDirection: "row", gap: 8 },
  actionChip: {
    alignItems: "center",
    borderColor: Design.colors.optionBorder,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  actionChipActive: { backgroundColor: "#EAF4EE", borderColor: Design.colors.primaryGreen },
  actionChipDisabled: { opacity: 0.55 },
  actionEmoji: { fontSize: 13 },
  actionCount: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption,
  },
  actionCountActive: { color: Design.colors.primaryGreen },
  commentList: { gap: 5, marginTop: 10 },
  commentRow: { flexDirection: "row", flexWrap: "wrap" },
  commentAuthor: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 1,
  },
  commentText: {
    color: Design.colors.black,
    flex: 1,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
  },
  commentComposer: {
    alignItems: "center",
    borderColor: "#E9E9E9",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    height: 40,
    marginTop: 10,
    paddingHorizontal: 12,
  },
  commentInput: {
    color: Design.colors.black,
    flex: 1,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    paddingVertical: 0,
  },
  centerState: { alignItems: "center", flex: 1, justifyContent: "center", padding: 24 },
  emptyTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
    marginTop: 14,
    textAlign: "center",
  },
  stateText: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
    marginTop: 8,
    textAlign: "center",
  },
  footerLoader: { paddingVertical: 12 },
  modalOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.45)",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  modalCard: {
    alignItems: "center",
    backgroundColor: Design.colors.white,
    borderRadius: 22,
    maxWidth: 380,
    padding: 26,
    width: "100%",
  },
  errorIcon: {
    alignItems: "center",
    backgroundColor: "#FDEAEA",
    borderRadius: 30,
    height: 58,
    justifyContent: "center",
    width: 58,
  },
  warningIcon: {
    alignItems: "center",
    backgroundColor: "#FDEAEA",
    borderRadius: 30,
    height: 58,
    justifyContent: "center",
    width: 58,
  },
  modalTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
    marginTop: 14,
    textAlign: "center",
  },
  modalMessage: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
    lineHeight: 20,
    marginTop: 8,
    textAlign: "center",
  },
  modalButton: {
    alignItems: "center",
    backgroundColor: Design.colors.primaryGreen,
    borderRadius: 22,
    marginTop: 22,
    minWidth: 140,
    paddingHorizontal: 24,
    paddingVertical: 11,
  },
  modalButtonText: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  confirmActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 22,
    width: "100%",
  },
  cancelButton: {
    alignItems: "center",
    borderColor: "#D8D8D8",
    borderRadius: 22,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 11,
  },
  cancelButtonText: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  deleteButton: {
    alignItems: "center",
    backgroundColor: "#B33A3A",
    borderRadius: 22,
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 11,
  },
});
