import { StyleSheet } from "react-native";
import { Design, FontFamily } from "@/src/constants/design";

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#F8FAF7",
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 32,
    paddingTop: 8,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "#F1F5F9",
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  headerSpacer: {
    width: 40,
  },
  title: {
    color: "#0F172A",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: 20,
  },
  rateCard: {
    alignItems: "center",
    backgroundColor: "#FFF1F2",
    borderColor: "#FECDD3",
    borderRadius: 18,
    borderWidth: 1.5,
    marginBottom: 24,
    padding: 18,
    shadowColor: "#E11D48",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  rateText: {
    color: "#9F1239",
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 1,
    marginBottom: 6,
  },
  rateValueRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  rateValue: {
    color: "#E11D48",
    fontFamily: FontFamily.poppinsSemiBold,
    fontSize: Design.fontSize.body + 2,
  },
  rateHint: {
    color: "#9F1239",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption,
    marginTop: 6,
    textAlign: "center",
  },
  rubyIcon: {
    height: 26,
    width: 26,
  },
  pricingError: {
    alignItems: "center",
  },
  retryButton: {
    borderColor: "#E11D48",
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  retryButtonText: {
    color: "#BE123C",
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption,
  },
  packagesSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    color: "#0F172A",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
    marginBottom: 12,
  },
  packagesLoading: {
    paddingVertical: 20,
  },
  packageCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    padding: 14,
  },
  packageInfo: {
    flex: 1,
    paddingRight: 8,
  },
  packageNameRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  packageName: {
    color: "#0F172A",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  packageTag: {
    borderRadius: 8,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: 10,
    overflow: "hidden",
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  popularTag: {
    backgroundColor: "#FEF3C7",
    color: "#92400E",
  },
  bestValueTag: {
    backgroundColor: "#D1FAE5",
    color: "#047857",
  },
  packageRuby: {
    color: "#475569",
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption,
    marginTop: 4,
  },
  packageBonus: {
    color: "#059669",
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption,
    marginTop: 2,
  },
  packagePrice: {
    alignItems: "flex-end",
  },
  packageBuyButton: {
    alignItems: "center",
    backgroundColor: "#10B981",
    borderRadius: 16,
    justifyContent: "center",
    marginTop: 8,
    minHeight: 34,
    minWidth: 76,
    paddingHorizontal: 14,
  },
  packageBuyLabel: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption,
  },
  packageCurrentPrice: {
    color: "#BE123C",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 1,
  },
  packageOriginalPrice: {
    color: "#94A3B8",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption - 1,
    textDecorationLine: "line-through",
  },
  packageDiscount: {
    color: "#059669",
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: 10,
    marginTop: 2,
  },
  packageLoadHint: {
    color: "#64748B",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption,
  },
  inputLabel: {
    color: "#0F172A",
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 2,
    marginBottom: 8,
  },
  inputWrap: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#D1FAE5",
    borderRadius: 16,
    borderWidth: 1.5,
    flexDirection: "row",
    marginBottom: 12,
    paddingHorizontal: 16,
    shadowColor: "#10B981",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  input: {
    color: "#0F172A",
    flex: 1,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.body,
    minHeight: 50,
  },
  amountPreview: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  amountLabel: {
    color: "#64748B",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
  },
  amountValue: {
    color: "#0F172A",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  minimumHint: {
    color: "#64748B",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption,
    marginBottom: 14,
    marginTop: -10,
  },
  errorText: {
    color: "#E11D48",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginBottom: 12,
  },
  submitButton: {
    alignItems: "center",
    backgroundColor: "#10B981",
    borderRadius: 999,
    justifyContent: "center",
    minHeight: 50,
    paddingHorizontal: 18,
    shadowColor: "#10B981",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 3,
  },
  disabledButton: {
    opacity: 0.5,
  },
  pressedButton: {
    transform: [{ scale: 0.98 }],
  },
  submitLabel: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  transactionCard: {
    alignItems: "center",
    backgroundColor: Design.colors.white,
    borderColor: "#E9E9E9",
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 24,
    padding: 16,
  },
  transactionTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
    marginBottom: 12,
    textAlign: "center",
  },
  qrCode: {
    height: 240,
    width: 240,
  },
  transactionSummary: {
    alignItems: "center",
    marginVertical: 12,
  },
  transactionRuby: {
    color: "#D9556D",
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
  },
  transactionAmount: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 2,
  },
  statusBadge: {
    borderRadius: 12,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  pendingStatus: {
    backgroundColor: "#FFF4E5",
  },
  successStatus: {
    backgroundColor: "#EAF4EE",
  },
  statusText: {
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 1,
  },
  pendingStatusText: {
    color: "#A15C00",
  },
  successStatusText: {
    color: Design.colors.primaryGreen,
  },
  walletBalanceRow: {
    alignItems: "center",
    alignSelf: "stretch",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  walletBalanceValue: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  smallRubyIcon: {
    height: 18,
    width: 18,
  },
  statusCheckSection: {
    alignItems: "center",
    alignSelf: "stretch",
    marginBottom: 10,
  },
  statusHint: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption,
    lineHeight: 18,
    marginBottom: 8,
    textAlign: "center",
  },
  checkStatusButton: {
    alignItems: "center",
    borderColor: Design.colors.primaryGreen,
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: 14,
  },
  checkStatusButtonText: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption,
  },
  statusErrorText: {
    color: "#B33A3A",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption,
    marginTop: 8,
    textAlign: "center",
  },
  details: {
    alignSelf: "stretch",
    borderTopColor: "#E9E9E9",
    borderTopWidth: 1,
    marginTop: 4,
    paddingTop: 10,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 7,
  },
  detailLabel: {
    color: Design.colors.mutedText,
    flexShrink: 0,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption,
  },
  detailValue: {
    color: Design.colors.black,
    flexShrink: 1,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption,
    textAlign: "right",
  },
  transferHint: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption,
    lineHeight: 18,
    marginTop: 12,
    textAlign: "center",
  },
});
