import { StyleSheet } from "react-native";
import { Design, FontFamily } from "@/src/constants/design";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: Design.colors.white },
  header: { paddingHorizontal: 24, paddingTop: 8 },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  title: {
    color: Design.colors.black,
    fontFamily: FontFamily.poppinsSemiBold,
    fontSize: Design.fontSize.h2 - 2,
    letterSpacing: 1,
    textAlign: "center",
  },
  subtitle: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
    marginBottom: 14,
    marginTop: 4,
    textAlign: "center",
  },
  searchBar: {
    alignItems: "center",
    borderColor: "#E9E9E9",
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    height: 40,
    marginBottom: 18,
    paddingHorizontal: 14,
  },
  searchInput: {
    color: Design.colors.black,
    flex: 1,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
    paddingVertical: 0,
  },
  listContent: { gap: 12, paddingBottom: 24, paddingHorizontal: 24 },
  emptyListContent: { flexGrow: 1 },
  goalCard: {
    backgroundColor: Design.colors.white,
    borderColor: "#E9E9E9",
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
  },
  cardPressed: { opacity: 0.8 },
  goalCardHeader: { flexDirection: "row", gap: 12 },
  goalIcon: {
    alignItems: "center",
    backgroundColor: "#EAF3ED",
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  goalTitleContainer: { flex: 1 },
  goalName: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
    lineHeight: 23,
  },
  goalId: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 2,
  },
  goalDetails: { gap: 8, marginTop: 16 },
  detailItem: { alignItems: "center", flexDirection: "row", gap: 8 },
  detailText: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
  },
  statusBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#FFF4DC",
    borderRadius: 12,
    marginTop: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusBadgeExpired: { backgroundColor: "#FDEAEA" },
  statusBadgeCompleted: { backgroundColor: "#EAF3ED" },
  statusText: {
    color: "#A16C00",
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 1,
  },
  statusTextExpired: { color: "#B33A3A" },
  statusTextCompleted: { color: Design.colors.primaryGreen },
  centerState: { alignItems: "center", flex: 1, justifyContent: "center", padding: 24 },
  stateText: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
    marginTop: 8,
    textAlign: "center",
  },
  emptyTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
    marginTop: 14,
    textAlign: "center",
  },
  weeksContent: { flexGrow: 1, paddingTop: 18 },
  weekOptionsContent: { flex: 1, paddingHorizontal: 24, paddingTop: 28 },
  weekOption: {
    alignItems: "center",
    backgroundColor: Design.colors.white,
    borderColor: "#E9E9E9",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
    padding: 16,
  },
  weekOptionIcon: {
    alignItems: "center",
    backgroundColor: "#EAF3ED",
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  weekOptionText: { flex: 1 },
  weekOptionTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
  },
  weekOptionHint: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 4,
  },
  photosContent: { paddingBottom: 32, paddingHorizontal: 24, paddingTop: 18 },
  clipsContent: { paddingBottom: 32, paddingHorizontal: 24, paddingTop: 18 },
  clipVideoCard: {
    backgroundColor: Design.colors.white,
    borderColor: "#E9E9E9",
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 16,
    overflow: "hidden",
  },
  clipVideo: { backgroundColor: "#111111", height: 210, width: "100%" },
  clipUnavailable: {
    alignItems: "center",
    backgroundColor: "#F2F2F2",
    height: 160,
    justifyContent: "center",
  },
  clipVideoDetails: { padding: 14 },
  socialPostButton: {
    alignItems: "center",
    backgroundColor: Design.colors.primaryGreen,
    borderRadius: 22,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  socialPostButtonText: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  clipVideoTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
  },
  clipVideoMeta: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 4,
  },
  photosHero: {
    alignItems: "center",
    backgroundColor: "#EAF3ED",
    borderRadius: 20,
    flexDirection: "row",
    padding: 16,
  },
  photosHeroIcon: {
    alignItems: "center",
    backgroundColor: Design.colors.white,
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  photosHeroText: { flex: 1, marginLeft: 12 },
  photosTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.poppinsSemiBold,
    fontSize: Design.fontSize.body,
    letterSpacing: 1,
  },
  photosRange: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 3,
  },
  photoCountBadge: { alignItems: "center", marginLeft: 8 },
  photoCount: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.poppinsSemiBold,
    fontSize: Design.fontSize.title,
  },
  photoCountLabel: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption,
    marginTop: -2,
  },
  photosSectionHeader: {
    alignItems: "baseline",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 24,
  },
  photosSectionTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
  },
  photosSectionHint: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 16,
    marginTop: 12,
  },
  photoItem: {
    backgroundColor: Design.colors.white,
    borderColor: "#E9E9E9",
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
    width: "48%",
  },
  photo: {
    backgroundColor: "#F2F2F2",
    aspectRatio: 0.86,
    width: "100%",
  },
  photoCaption: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    minHeight: 38,
    paddingHorizontal: 10,
  },
  photoDate: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
  },
  emptyPhotosCard: {
    alignItems: "center",
    backgroundColor: "#F8FAF8",
    borderColor: "#EAF3ED",
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  selectedCount: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 1,
  },
  photosSelectionActions: {
    alignItems: "flex-end",
    gap: 5,
  },
  selectAllButton: {
    alignItems: "center",
    backgroundColor: Design.colors.primaryGreen,
    borderRadius: 18,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  selectAllButtonText: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 1,
  },
  disabledButton: { opacity: 0.45 },
  photoItemSelected: {
    borderColor: Design.colors.primaryGreen,
    borderWidth: 2,
  },
  selectionMessage: {
    color: "#B33A3A",
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 14,
    textAlign: "center",
  },
  createClipButton: {
    alignItems: "center",
    backgroundColor: Design.colors.primaryGreen,
    borderRadius: 26,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginTop: 18,
    paddingVertical: 14,
  },
  minimumPhotosHint: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 18,
    textAlign: "center",
  },
  createClipButtonText: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
  },
  clipProgressCard: {
    backgroundColor: "#F8FAF8",
    borderColor: "#EAF3ED",
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 18,
    padding: 14,
  },
  clipProgressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  clipProgressTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  clipProgressPercent: {
    color: Design.colors.primaryGreen,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  progressTrack: {
    backgroundColor: "#DCE8DF",
    borderRadius: 4,
    height: 8,
    marginTop: 10,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: Design.colors.primaryGreen,
    borderRadius: 4,
    height: "100%",
  },
  clipProgressText: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 8,
  },
  clipErrorText: {
    color: "#B33A3A",
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 4,
  },
  weeksGoalName: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
    paddingHorizontal: 24,
    textAlign: "center",
  },
  goalHint: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
    marginTop: 6,
    paddingHorizontal: 24,
    textAlign: "center",
  },
  weekStack: { flexGrow: 1, marginTop: 22 },
  weekCard: {
    alignItems: "flex-start",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    flexDirection: "row",
    flexGrow: 1,
    justifyContent: "space-between",
    minHeight: 108,
    paddingHorizontal: 22,
    paddingTop: 28,
  },
  weekCardOverlap: { marginTop: -30 },
  weekInfo: { flex: 1 },
  weekTitle: {
    color: Design.colors.white,
    fontFamily: FontFamily.poppinsSemiBold,
    fontSize: Design.fontSize.title,
    letterSpacing: 1,
  },
  weekDate: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 6,
  },
  weekProgress: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 1,
    marginTop: 4,
  },
  weekAction: { alignItems: "flex-end", gap: 16 },
  currentLabel: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption,
  },
  modalOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.45)",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  errorModal: {
    alignItems: "center",
    backgroundColor: Design.colors.white,
    borderRadius: 22,
    maxWidth: 380,
    paddingHorizontal: 24,
    paddingVertical: 26,
    width: "100%",
  },
  resultModal: {
    alignItems: "center",
    backgroundColor: Design.colors.white,
    borderRadius: 22,
    maxWidth: 380,
    paddingHorizontal: 24,
    paddingVertical: 26,
    width: "100%",
  },
  resultIcon: {
    alignItems: "center",
    backgroundColor: "#EAF3ED",
    borderRadius: 30,
    height: 60,
    justifyContent: "center",
    marginBottom: 14,
    width: 60,
  },
  resultIconFailed: { backgroundColor: "#FDEAEA" },
  errorIcon: {
    alignItems: "center",
    backgroundColor: "#FDEAEA",
    borderRadius: 28,
    height: 56,
    justifyContent: "center",
    marginBottom: 14,
    width: 56,
  },
  errorModalTitle: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.body,
    textAlign: "center",
  },
  errorModalMessage: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamRegular,
    fontSize: Design.fontSize.caption + 2,
    lineHeight: 20,
    marginTop: 8,
    textAlign: "center",
  },
  modalButton: {
    alignItems: "center",
    backgroundColor: Design.colors.primaryGreen,
    borderRadius: 22,
    marginTop: 22,
    minWidth: 140,
    paddingHorizontal: 24,
    paddingVertical: 11,
  },
  modalButtonText: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamSemiBold,
    fontSize: Design.fontSize.caption + 2,
  },
  photoActionModal: {
    backgroundColor: Design.colors.white,
    borderRadius: 22,
    maxWidth: 380,
    padding: 22,
    width: "100%",
  },
  modalOption: {
    alignItems: "center",
    borderColor: "#E9E9E9",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginTop: 12,
    padding: 14,
  },
  modalOptionText: {
    color: Design.colors.black,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.body,
  },
  modalCancelButton: { alignItems: "center", marginTop: 16, padding: 8 },
  modalCancelText: {
    color: Design.colors.mutedText,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 2,
  },
  viewerOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.92)",
    flex: 1,
    justifyContent: "center",
    padding: 20,
  },
  viewerClose: {
    position: "absolute",
    right: 20,
    top: 50,
    zIndex: 1,
  },
  viewerImage: { height: "78%", width: "100%" },
  viewerDate: {
    color: Design.colors.white,
    fontFamily: FontFamily.beVietnamMedium,
    fontSize: Design.fontSize.caption + 2,
    marginTop: 12,
  },
});
